replaced user-specific debian init script template with an actually working mesosphere-compatible one

diff --git a/bin/chronos.debian.init b/bin/chronos.debian.init
--- a/bin/chronos.debian.init
+++ b/bin/chronos.debian.init
@@ -1,103 +1,102 @@
 #!/bin/sh
-# Start/stop the chronos.
-#
 ### BEGIN INIT INFO
 # Provides:          chronos
-# Required-Start:    $remote_fs $syslog $time
-# Required-Stop:     $remote_fs $syslog $time
-# Should-Start:      $network $named slapd autofs ypbind nscd nslcd
-# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd
+# Required-Start:    $remote_fs $network
+# Required-Stop:     $remote_fs $network
 # Default-Start:     2 3 4 5
-# Default-Stop:
-# Short-Description: chronos is airbnb's replacement for cron.
-# Description:       chronos is a distributed and fault-tolerant scheduler
-#                    which runs on top of mesos. It's a framework and supports
-#                    custom mesos executors as well as the default command
-#                    executor. Thus by default, Chronos executes sh (on most
-#                    systems bash) scripts. Chronos can be used to interact
-#                    with systems such as Hadoop (incl. EMR), even if the
-#                    mesos slaves on which execution happens do not have
-#                    Hadoop installed. Included wrapper scripts allow
-#                    transfering files and executing them on a remote machine
-#                    in the background and using asynchronous callbacks to
-#                    notify Chronos of job completion or failures.
-#                    See https://github.com/airbnb/chronos for more info.
+# Default-Stop:      0 1 6
+# Short-Description: chronos
+# Description:       Chronos scheduler for Mesos
 ### END INIT INFO
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-DESC="chronos daemon"
+# Author: Ilya Epifanov <elijah.epifanov@gmail.com>
+
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Chronos scheduler for Mesos"
 NAME=chronos
-DAEMON=/usr/bin/java
-PIDFILE=/var/run/${NAME}.pid
-SCRIPTNAME=$0
+DAEMON=/usr/local/bin/chronos
+DAEMON_ARGS=""
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-# set these to match your environment
-CHRONOS_HOME=/home/asemenov/chronos
-MESOS_HOME=/opt/mesos
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-if [ "$(id -u)" -ne "0" ]; then
-  echo "you must be root to start ${DESC}"
-  exit 1
-fi
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 . /lib/lsb/init-functions
 
-[ -r /etc/default/chronos ] && . /etc/default/chronos
+do_start() {
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    pid=$(pidofproc -p $PIDFILE $DAEMON)
+    if [ -n "$pid" ] ; then
+        return 1
+    fi
 
-# Read the system's locale and set cron's locale. This is only used for
-# setting the charset of mails generated by cron. To provide locale
-# information to tasks running under cron, see /etc/pam.d/cron.
-#
-# We read /etc/environment, but warn about locale information in
-# there because it should be in /etc/default/locale.
-set_environment () {
-  libmesos_file=$(find ${MESOS_HOME} -name "libmesos.dylib" -or -name "libmesos.so" | head -n1)
-  build_env=$(find ${MESOS_HOME} -name "mesos-build-env.sh" | head -n1)
-  chronos_jar_file=$(find ${CHRONOS_HOME} -name "chronos-*.jar" | grep -v sources | head -n1)
-  export MESOS_NATIVE_LIBRARY="${libmesos_file}"
-  . $build_env
-  EXTRA_OPTS="-cp $chronos_jar_file com.airbnb.scheduler.Main server "$CHRONOS_HOME"/config/local_scheduler_nozk.yml"
+    start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- \
+            $DAEMON_ARGS \
+            || return 2
+}
+
+do_stop() {
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+    rm -f $PIDFILE
+    return "$RETVAL"
 }
 
 case "$1" in
-  start)
-    set_environment
-    log_daemon_msg "Starting periodic command scheduler" "cron"
-    ### example starting chronos from command line
-    ### java -cp $chronos_jar_file com.airbnb.scheduler.Main server "$CHRONOS_HOME"/config/local_scheduler_nozk.yml 
-    ### example startin chronos with start_daemon
-    ### start_daemon -p $PIDFILE $DAEMON $EXTRA_OPTS
-
-    # best way to daemonize, imho
-    start-stop-daemon --start --quiet --background \
-        --pidfile $PIDFILE --make-pidfile \
-        --exec $DAEMON -- $EXTRA_OPTS
-    log_end_msg $?
-  ;;
-  stop)
-    log_daemon_msg "Stopping periodic command scheduler" "${NAME}"
-    killproc -p $PIDFILE $DAEMON
-    RETVAL=$?
-    [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
-    log_end_msg $RETVAL
-  ;;
-  restart)
-    log_daemon_msg "Restarting periodic command scheduler" "${NAME}" 
-    $0 stop
-    sleep 5
-    $0 start
-  ;;
-  reload|force-reload)
-    log_daemon_msg "Reloading configuration files for periodic command scheduler" "${NAME}"
-    # cron reloads automatically
-    log_end_msg 0
-  ;;
-  status)
-    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
-    ;;
-  *)
-    log_action_msg "Usage: ${SCRIPTNAME} {start|stop|status|restart|reload|force-reload}"
-    exit 2
-  ;;
+    start)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        do_start
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+              2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    stop)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+              2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    status)
+        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+        ;;
+    restart|force-reload)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_stop
+        case "$?" in
+          0|1)
+              do_start
+              case "$?" in
+                  0) log_end_msg 0 ;;
+                  1) log_end_msg 1 ;; # Old process is still running
+                  *) log_end_msg 1 ;; # Failed to start
+              esac
+              ;;
+          *)
+              # Failed to stop
+              log_end_msg 1
+              ;;
+        esac
+        ;;
+    *)
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+        exit 3
+        ;;
 esac
+
 exit 0
